### PR TITLE
Spanish translation

### PR DESCRIPTION
**Pull request by ivanhercaz**
Hi @HenriDellal,
First of all, thank you to you and to all the contributors of Emeral for this awesome, easy to use and minimalistic launcher. Well, I wanted to contribute to this project with a new translation to Spanish.

I translated all the files I understand they are translatable, because there are another files without text to translate. The files translated are:

- `arrays.xml`
- `cwac_colormixer_strings.xml`
- `strings.xml`

I have one suggestion too: why the last string in `strings.xml` is untranslatable? It is easy to translate and if we translate it we could make easier to share with everyone the contributions of each one and  to encourage users to "Want to help? Report bugs and submit suggestions via...". What do you think about it?

### CODE REVIEW

**Comment by HenriDellal** [comment]
Hello.
Thank you very much for help, going to merge the PR soon.
The text on about screen is not for translation yet, though I'd like to make it translatable in the future. The reason is that I'd like to change the about screen UI and move information about contributors into arrays.xml so it's easier to maintain translations.

**Comment by ivanhercaz** [comment]
All right! Good idea. So I am not going to add the about translation in this PR and when you have made the improvement, I will translate it.

**Comment by ivanhercaz** [comment]
@HenriDellal, if you prefer I can review again the code to clean it of the strings with translatable parameter set to false. I could avoid you time to review the strings.

**Comment by HenriDellal** [comment]
Thank you. I will do it myself, have to review the translation anyway.

**Comment by HenriDellal** [comment]
Everything is fine, no need to apologize. Thanks!

**Pull request merged**
