### PR TITLE
Fix #54

### LINKED ISSUE #54: Main bar hidden under home touch buttons
I've only seen this on a phone, which happens to be Android 5.1.1.

When the "main bar" is at the bottom, touching the "main bar" menu causes the "main bar" to drop below the "home touch" buttons so that the menu button of 3 dots, nor the categories bar can be pressed.  Restarting emerald fixes the problem until the "main bar" menu button is touched (something else may trigger this problem also I believe, though I'm not sure of the exact circumstances).  Normally the "main bar" sits above the "home touch" bar until this bug is triggered.

This behavior also occurs when the main bar is at top, but is less noticeable as it only can be seen if there are enough icons to fill the screen, or if icons are positioned starting from the bottom (by the option "Stick category content to the bottom").  When triggered, icons will be hidden behind the "home touch" bar (scrolling all the way up leaves a row of icons behind the "home touch" bar).

### PR DESCRIPTION
**Pull request by FliegendeWurst**
I was also affected by #54, and this fix works for me.

Oh and btw, why was #69 "unmerged"?

### CODE REVIEW

**Comment by HenriDellal** [comment]
Hello.
Thank you for the contribution. It is cool that it works, I'll merge it soon.
As for #69, I didn't unmerge it and it works as usual.

**Comment by HenriDellal** [comment]
Oh...
It somehow removes previous merges when I upload something.

**Comment by HenriDellal** [comment]
Oh...
It somehow removes previous merges when I upload something.

**Comment by HenriDellal** [comment]
Now I see. Just didn't pull changes on my side before editing. Sorry.

**Comment by FliegendeWurst** [comment]
It's ok, nobody is perfect, especially not at git..

**Pull request merged**
